<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

$classLoader = new Composer\Autoload\ClassLoader();
$classLoader->setPsr4('ColibriLabs\Database\Om\\', __DIR__);
$classLoader->register(true);

return $classLoader;