<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

/**
 * Class BackdropRepository
 * @package ColibriLabs\Database\Om
 */
class BackdropRepository extends Base\BaseBackdropRepository
{
  
}