<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class BackdropRepository extends Base\BaseBackdropRepository
{
  // ... write your custom code here
}