<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class CharacterRepository extends Base\BaseCharacterRepository
{
  // ... write your custom code here
}