<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

/**
 * Class Character
 * @package ColibriLabs\Database\Om
 */
class Character extends Base\BaseCharacter
{
  
  /**
   * @var Profile
   */
  protected $profile;
  
  /**
   * @return Profile
   */
  public function getProfile()
  {
    return $this->profile;
  }
  
  /**
   * @param Profile $profile
   */
  public function setProfile(Profile $profile)
  {
    $this->profile = $profile;
  }
  
}