<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class CollectionPoster extends Base\BaseCollectionPoster
{
  // ... write your custom code here
}