<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class CollectionRepository extends Base\BaseCollectionRepository
{
  // ... write your custom code here
}