<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class CollectionBackdropRepository extends Base\BaseCollectionBackdropRepository
{
  // ... write your custom code here
}