<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class Collection extends Base\BaseCollection
{
  // ... write your custom code here
}