<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class CollectionPosterRepository extends Base\BaseCollectionPosterRepository
{
  // ... write your custom code here
}