<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class CollectionBackdrop extends Base\BaseCollectionBackdrop
{
  // ... write your custom code here
}