<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class CompanyRepository extends Base\BaseCompanyRepository
{
  // ... write your custom code here
}