<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class CountryRepository extends Base\BaseCountryRepository
{
  // ... write your custom code here
}