<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class CrewRepository extends Base\BaseCrewRepository
{
  // ... write your custom code here
}