<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class GenreRepository extends Base\BaseGenreRepository
{
  // ... write your custom code here
}