<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class LanguageRepository extends Base\BaseLanguageRepository
{
  // ... write your custom code here
}