<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

return array (
  'ColibriLabs\\Database\\Om\\Movie' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\Movie',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\MovieRepository',
    'tableName' => 'movies',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'movies.id',
      'collection_id' => 'movies.collection_id',
      'tmdb_id' => 'movies.tmdb_id',
      'imdb_id' => 'movies.imdb_id',
      'budget' => 'movies.budget',
      'revenue' => 'movies.revenue',
      'runtime' => 'movies.runtime',
      'adult' => 'movies.adult',
      'release_date' => 'movies.release_date',
      'title' => 'movies.title',
      'original_title' => 'movies.original_title',
      'iso_language' => 'movies.iso_language',
      'overview' => 'movies.overview',
      'tagline' => 'movies.tagline',
      'tmdb_votes' => 'movies.tmdb_votes',
      'tmdb_rating' => 'movies.tmdb_rating',
      'imdb_votes' => 'movies.imdb_votes',
      'imdb_rating' => 'movies.imdb_rating',
      'mpaa_rating' => 'movies.mpaa_rating',
      'version' => 'movies.version',
      'created' => 'movies.created',
      'updated' => 'movies.updated',
    ),
    'names' => 
    array (
      'id' => 'id',
      'collection_id' => 'collection_id',
      'tmdb_id' => 'tmdb_id',
      'imdb_id' => 'imdb_id',
      'budget' => 'budget',
      'revenue' => 'revenue',
      'runtime' => 'runtime',
      'adult' => 'adult',
      'release_date' => 'release_date',
      'title' => 'title',
      'original_title' => 'original_title',
      'iso_language' => 'iso_language',
      'overview' => 'overview',
      'tagline' => 'tagline',
      'tmdb_votes' => 'tmdb_votes',
      'tmdb_rating' => 'tmdb_rating',
      'imdb_votes' => 'imdb_votes',
      'imdb_rating' => 'imdb_rating',
      'mpaa_rating' => 'mpaa_rating',
      'version' => 'version',
      'created' => 'created',
      'updated' => 'updated',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
      'mpaa_rating' => 
      array (
        0 => 'G',
        1 => 'PG',
        2 => 'PG-13',
        3 => 'R',
        4 => 'NC-17',
      ),
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'collection_id' => 'collection_id',
      'tmdb_id' => 'tmdb_id',
      'imdb_id' => 'imdb_id',
      'budget' => 'budget',
      'revenue' => 'revenue',
      'runtime' => 'runtime',
      'tmdb_votes' => 'tmdb_votes',
      'imdb_votes' => 'imdb_votes',
      'version' => 'version',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'collection_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'collection_id',
         'name' => 'collection_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'tmdb_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'tmdb_id',
         'name' => 'tmdb_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'imdb_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'imdb_id',
         'name' => 'imdb_id',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 9,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'budget' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'budget',
         'name' => 'budget',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'revenue' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'revenue',
         'name' => 'revenue',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'runtime' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'runtime',
         'name' => 'runtime',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'adult' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'adult',
         'name' => 'adult',
         'type' => 
        Colibri\Schema\Types\BooleanType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'release_date' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'release_date',
         'name' => 'release_date',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'title' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'title',
         'name' => 'title',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 255,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'original_title' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'original_title',
         'name' => 'original_title',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 255,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'iso_language' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'iso_language',
         'name' => 'iso_language',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 2,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'overview' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'overview',
         'name' => 'overview',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'tagline' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'tagline',
         'name' => 'tagline',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'tmdb_votes' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'tmdb_votes',
         'name' => 'tmdb_votes',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'tmdb_rating' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'tmdb_rating',
         'name' => 'tmdb_rating',
         'type' => 
        Colibri\Schema\Types\FloatType::__set_state(array(
           'length' => 10,
           'precision' => 4,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'imdb_votes' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'imdb_votes',
         'name' => 'imdb_votes',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'imdb_rating' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'imdb_rating',
         'name' => 'imdb_rating',
         'type' => 
        Colibri\Schema\Types\FloatType::__set_state(array(
           'length' => 10,
           'precision' => 4,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'mpaa_rating' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'mpaa_rating',
         'name' => 'mpaa_rating',
         'type' => 
        Colibri\Schema\Types\EnumType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => 
          array (
            0 => 'G',
            1 => 'PG',
            2 => 'PG-13',
            3 => 'R',
            4 => 'NC-17',
          ),
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'version' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'version',
         'name' => 'version',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'created' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'created',
         'name' => 'created',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'updated' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'updated',
         'name' => 'updated',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\MovieGenre' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\MovieGenre',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\MovieGenreRepository',
    'tableName' => 'movie_genre',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'movie_genre.id',
      'movie_id' => 'movie_genre.movie_id',
      'genre_id' => 'movie_genre.genre_id',
    ),
    'names' => 
    array (
      'id' => 'id',
      'movie_id' => 'movie_id',
      'genre_id' => 'genre_id',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'movie_id' => 'movie_id',
      'genre_id' => 'genre_id',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'movie_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'movie_id',
         'name' => 'movie_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'genre_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'genre_id',
         'name' => 'genre_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\MovieCompany' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\MovieCompany',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\MovieCompanyRepository',
    'tableName' => 'movie_company',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'movie_company.id',
      'movie_id' => 'movie_company.movie_id',
      'company_id' => 'movie_company.company_id',
    ),
    'names' => 
    array (
      'id' => 'id',
      'movie_id' => 'movie_id',
      'company_id' => 'company_id',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'movie_id' => 'movie_id',
      'company_id' => 'company_id',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'movie_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'movie_id',
         'name' => 'movie_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'company_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'company_id',
         'name' => 'company_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\MovieCountry' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\MovieCountry',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\MovieCountryRepository',
    'tableName' => 'movie_country',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'movie_country.id',
      'movie_id' => 'movie_country.movie_id',
      'country_id' => 'movie_country.country_id',
    ),
    'names' => 
    array (
      'id' => 'id',
      'movie_id' => 'movie_id',
      'country_id' => 'country_id',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'movie_id' => 'movie_id',
      'country_id' => 'country_id',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'movie_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'movie_id',
         'name' => 'movie_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'country_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'country_id',
         'name' => 'country_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\MovieLanguage' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\MovieLanguage',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\MovieLanguageRepository',
    'tableName' => 'movie_language',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'movie_language.id',
      'movie_id' => 'movie_language.movie_id',
      'language_id' => 'movie_language.language_id',
    ),
    'names' => 
    array (
      'id' => 'id',
      'movie_id' => 'movie_id',
      'language_id' => 'language_id',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'movie_id' => 'movie_id',
      'language_id' => 'language_id',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'movie_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'movie_id',
         'name' => 'movie_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'language_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'language_id',
         'name' => 'language_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\Collection' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\Collection',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\CollectionRepository',
    'tableName' => 'collections',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'collections.id',
      'tmdb_id' => 'collections.tmdb_id',
      'name' => 'collections.name',
      'version' => 'collections.version',
      'created' => 'collections.created',
      'updated' => 'collections.updated',
    ),
    'names' => 
    array (
      'id' => 'id',
      'tmdb_id' => 'tmdb_id',
      'name' => 'name',
      'version' => 'version',
      'created' => 'created',
      'updated' => 'updated',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'tmdb_id' => 'tmdb_id',
      'version' => 'version',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'tmdb_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'tmdb_id',
         'name' => 'tmdb_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'name' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'name',
         'name' => 'name',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 255,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'version' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'version',
         'name' => 'version',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'created' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'created',
         'name' => 'created',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'updated' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'updated',
         'name' => 'updated',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\CollectionPoster' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\CollectionPoster',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\CollectionPosterRepository',
    'tableName' => 'collection_posters',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'collection_posters.id',
      'picture_id' => 'collection_posters.picture_id',
      'collection_id' => 'collection_posters.collection_id',
    ),
    'names' => 
    array (
      'id' => 'id',
      'picture_id' => 'picture_id',
      'collection_id' => 'collection_id',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'picture_id' => 'picture_id',
      'collection_id' => 'collection_id',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'picture_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'picture_id',
         'name' => 'picture_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'collection_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'collection_id',
         'name' => 'collection_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\CollectionBackdrop' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\CollectionBackdrop',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\CollectionBackdropRepository',
    'tableName' => 'collection_backdrops',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'collection_backdrops.id',
      'picture_id' => 'collection_backdrops.picture_id',
      'collection_id' => 'collection_backdrops.collection_id',
    ),
    'names' => 
    array (
      'id' => 'id',
      'picture_id' => 'picture_id',
      'collection_id' => 'collection_id',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'picture_id' => 'picture_id',
      'collection_id' => 'collection_id',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'picture_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'picture_id',
         'name' => 'picture_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'collection_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'collection_id',
         'name' => 'collection_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\Company' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\Company',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\CompanyRepository',
    'tableName' => 'companies',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'companies.id',
      'tmdb_id' => 'companies.tmdb_id',
      'name' => 'companies.name',
      'version' => 'companies.version',
      'created' => 'companies.created',
      'updated' => 'companies.updated',
    ),
    'names' => 
    array (
      'id' => 'id',
      'tmdb_id' => 'tmdb_id',
      'name' => 'name',
      'version' => 'version',
      'created' => 'created',
      'updated' => 'updated',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'tmdb_id' => 'tmdb_id',
      'version' => 'version',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'tmdb_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'tmdb_id',
         'name' => 'tmdb_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'name' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'name',
         'name' => 'name',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 255,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'version' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'version',
         'name' => 'version',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'created' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'created',
         'name' => 'created',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'updated' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'updated',
         'name' => 'updated',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\Country' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\Country',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\CountryRepository',
    'tableName' => 'countries',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'countries.id',
      'iso_3166_1' => 'countries.iso_3166_1',
      'name' => 'countries.name',
      'version' => 'countries.version',
      'created' => 'countries.created',
      'updated' => 'countries.updated',
    ),
    'names' => 
    array (
      'id' => 'id',
      'iso_3166_1' => 'iso_3166_1',
      'name' => 'name',
      'version' => 'version',
      'created' => 'created',
      'updated' => 'updated',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'version' => 'version',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'iso_3166_1' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'iso_3166_1',
         'name' => 'iso_3166_1',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 2,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'name' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'name',
         'name' => 'name',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 255,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'version' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'version',
         'name' => 'version',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'created' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'created',
         'name' => 'created',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'updated' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'updated',
         'name' => 'updated',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\Language' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\Language',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\LanguageRepository',
    'tableName' => 'languages',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'languages.id',
      'iso_639_1' => 'languages.iso_639_1',
      'name' => 'languages.name',
      'version' => 'languages.version',
      'created' => 'languages.created',
      'updated' => 'languages.updated',
    ),
    'names' => 
    array (
      'id' => 'id',
      'iso_639_1' => 'iso_639_1',
      'name' => 'name',
      'version' => 'version',
      'created' => 'created',
      'updated' => 'updated',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'version' => 'version',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'iso_639_1' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'iso_639_1',
         'name' => 'iso_639_1',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 2,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'name' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'name',
         'name' => 'name',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 255,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'version' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'version',
         'name' => 'version',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'created' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'created',
         'name' => 'created',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'updated' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'updated',
         'name' => 'updated',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\Genre' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\Genre',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\GenreRepository',
    'tableName' => 'genres',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'genres.id',
      'tmdb_id' => 'genres.tmdb_id',
      'name' => 'genres.name',
      'version' => 'genres.version',
      'created' => 'genres.created',
      'updated' => 'genres.updated',
    ),
    'names' => 
    array (
      'id' => 'id',
      'tmdb_id' => 'tmdb_id',
      'name' => 'name',
      'version' => 'version',
      'created' => 'created',
      'updated' => 'updated',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'tmdb_id' => 'tmdb_id',
      'version' => 'version',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'tmdb_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'tmdb_id',
         'name' => 'tmdb_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'name' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'name',
         'name' => 'name',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 64,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'version' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'version',
         'name' => 'version',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'created' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'created',
         'name' => 'created',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'updated' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'updated',
         'name' => 'updated',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\Character' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\Character',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\CharacterRepository',
    'tableName' => 'characters',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'characters.id',
      'tmdb_id' => 'characters.tmdb_id',
      'profile_id' => 'characters.profile_id',
      'movie_id' => 'characters.movie_id',
      'character' => 'characters.character',
      'order' => 'characters.order',
      'version' => 'characters.version',
      'created' => 'characters.created',
      'updated' => 'characters.updated',
    ),
    'names' => 
    array (
      'id' => 'id',
      'tmdb_id' => 'tmdb_id',
      'profile_id' => 'profile_id',
      'movie_id' => 'movie_id',
      'character' => 'character',
      'order' => 'order',
      'version' => 'version',
      'created' => 'created',
      'updated' => 'updated',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'tmdb_id' => 'tmdb_id',
      'profile_id' => 'profile_id',
      'movie_id' => 'movie_id',
      'order' => 'order',
      'version' => 'version',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'tmdb_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'tmdb_id',
         'name' => 'tmdb_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'profile_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'profile_id',
         'name' => 'profile_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'movie_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'movie_id',
         'name' => 'movie_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'character' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'character',
         'name' => 'character',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 64,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'order' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'order',
         'name' => 'order',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 3,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'version' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'version',
         'name' => 'version',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'created' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'created',
         'name' => 'created',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'updated' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'updated',
         'name' => 'updated',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\Crew' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\Crew',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\CrewRepository',
    'tableName' => 'crews',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'crews.id',
      'tmdb_id' => 'crews.tmdb_id',
      'profile_id' => 'crews.profile_id',
      'movie_id' => 'crews.movie_id',
      'department' => 'crews.department',
      'job' => 'crews.job',
      'order' => 'crews.order',
      'version' => 'crews.version',
      'created' => 'crews.created',
      'updated' => 'crews.updated',
    ),
    'names' => 
    array (
      'id' => 'id',
      'tmdb_id' => 'tmdb_id',
      'profile_id' => 'profile_id',
      'movie_id' => 'movie_id',
      'department' => 'department',
      'job' => 'job',
      'order' => 'order',
      'version' => 'version',
      'created' => 'created',
      'updated' => 'updated',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'tmdb_id' => 'tmdb_id',
      'profile_id' => 'profile_id',
      'movie_id' => 'movie_id',
      'order' => 'order',
      'version' => 'version',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'tmdb_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'tmdb_id',
         'name' => 'tmdb_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'profile_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'profile_id',
         'name' => 'profile_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'movie_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'movie_id',
         'name' => 'movie_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'department' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'department',
         'name' => 'department',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 64,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'job' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'job',
         'name' => 'job',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 64,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'order' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'order',
         'name' => 'order',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 3,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'version' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'version',
         'name' => 'version',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'created' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'created',
         'name' => 'created',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'updated' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'updated',
         'name' => 'updated',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\Profile' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\Profile',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\ProfileRepository',
    'tableName' => 'profiles',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'profiles.id',
      'tmdb_id' => 'profiles.tmdb_id',
      'imdb_id' => 'profiles.imdb_id',
      'name' => 'profiles.name',
      'biography' => 'profiles.biography',
      'adult' => 'profiles.adult',
      'sex' => 'profiles.sex',
      'birthday' => 'profiles.birthday',
      'deathday' => 'profiles.deathday',
      'version' => 'profiles.version',
      'created' => 'profiles.created',
      'updated' => 'profiles.updated',
    ),
    'names' => 
    array (
      'id' => 'id',
      'tmdb_id' => 'tmdb_id',
      'imdb_id' => 'imdb_id',
      'name' => 'name',
      'biography' => 'biography',
      'adult' => 'adult',
      'sex' => 'sex',
      'birthday' => 'birthday',
      'deathday' => 'deathday',
      'version' => 'version',
      'created' => 'created',
      'updated' => 'updated',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'tmdb_id' => 'tmdb_id',
      'sex' => 'sex',
      'version' => 'version',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'tmdb_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'tmdb_id',
         'name' => 'tmdb_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'imdb_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'imdb_id',
         'name' => 'imdb_id',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 9,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'name' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'name',
         'name' => 'name',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 64,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'biography' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'biography',
         'name' => 'biography',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'adult' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'adult',
         'name' => 'adult',
         'type' => 
        Colibri\Schema\Types\BooleanType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'sex' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'sex',
         'name' => 'sex',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 1,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'birthday' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'birthday',
         'name' => 'birthday',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'deathday' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'deathday',
         'name' => 'deathday',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'version' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'version',
         'name' => 'version',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'created' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'created',
         'name' => 'created',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'updated' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'updated',
         'name' => 'updated',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\Photo' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\Photo',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\PhotoRepository',
    'tableName' => 'photos',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'photos.id',
      'picture_id' => 'photos.picture_id',
      'profile_id' => 'photos.profile_id',
    ),
    'names' => 
    array (
      'id' => 'id',
      'picture_id' => 'picture_id',
      'profile_id' => 'profile_id',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'picture_id' => 'picture_id',
      'profile_id' => 'profile_id',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'picture_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'picture_id',
         'name' => 'picture_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'profile_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'profile_id',
         'name' => 'profile_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\Backdrop' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\Backdrop',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\BackdropRepository',
    'tableName' => 'backdrops',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'backdrops.id',
      'picture_id' => 'backdrops.picture_id',
      'movie_id' => 'backdrops.movie_id',
    ),
    'names' => 
    array (
      'id' => 'id',
      'picture_id' => 'picture_id',
      'movie_id' => 'movie_id',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'picture_id' => 'picture_id',
      'movie_id' => 'movie_id',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'picture_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'picture_id',
         'name' => 'picture_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'movie_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'movie_id',
         'name' => 'movie_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\Poster' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\Poster',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\PosterRepository',
    'tableName' => 'posters',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'posters.id',
      'picture_id' => 'posters.picture_id',
      'movie_id' => 'posters.movie_id',
    ),
    'names' => 
    array (
      'id' => 'id',
      'picture_id' => 'picture_id',
      'movie_id' => 'movie_id',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'picture_id' => 'picture_id',
      'movie_id' => 'movie_id',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'picture_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'picture_id',
         'name' => 'picture_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'movie_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'movie_id',
         'name' => 'movie_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\Picture' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\Picture',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\PictureRepository',
    'tableName' => 'pictures',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'pictures.id',
      'height' => 'pictures.height',
      'width' => 'pictures.width',
      'file_path' => 'pictures.file_path',
      'tmdb_file_path' => 'pictures.tmdb_file_path',
      'iso_639_1' => 'pictures.iso_639_1',
      'version' => 'pictures.version',
      'created' => 'pictures.created',
      'updated' => 'pictures.updated',
    ),
    'names' => 
    array (
      'id' => 'id',
      'height' => 'height',
      'width' => 'width',
      'file_path' => 'file_path',
      'tmdb_file_path' => 'tmdb_file_path',
      'iso_639_1' => 'iso_639_1',
      'version' => 'version',
      'created' => 'created',
      'updated' => 'updated',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'height' => 'height',
      'width' => 'width',
      'version' => 'version',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'height' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'height',
         'name' => 'height',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'width' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'width',
         'name' => 'width',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'file_path' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'file_path',
         'name' => 'file_path',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 128,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'tmdb_file_path' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'tmdb_file_path',
         'name' => 'tmdb_file_path',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 64,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'iso_639_1' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'iso_639_1',
         'name' => 'iso_639_1',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 2,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'version' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'version',
         'name' => 'version',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'created' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'created',
         'name' => 'created',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'updated' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'updated',
         'name' => 'updated',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\User' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\User',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\UserRepository',
    'tableName' => 'admin_users',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'admin_users.id',
      'email' => 'admin_users.email',
      'settings' => 'admin_users.settings',
      'login' => 'admin_users.login',
      'password' => 'admin_users.password',
    ),
    'names' => 
    array (
      'id' => 'id',
      'email' => 'email',
      'settings' => 'settings',
      'login' => 'login',
      'password' => 'password',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'email' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'email',
         'name' => 'email',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 64,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'settings' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'settings',
         'name' => 'settings',
         'type' => 
        Colibri\Schema\Types\JsonType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'login' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'login',
         'name' => 'login',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 64,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'password' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'password',
         'name' => 'password',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 64,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\UserSession' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\UserSession',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\UserSessionRepository',
    'tableName' => 'admin_user_sessions',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'admin_user_sessions.id',
      'user_id' => 'admin_user_sessions.user_id',
      'session_id' => 'admin_user_sessions.session_id',
      'ip' => 'admin_user_sessions.ip',
      'user_agent' => 'admin_user_sessions.user_agent',
      'os' => 'admin_user_sessions.os',
      'browser' => 'admin_user_sessions.browser',
      'device_type' => 'admin_user_sessions.device_type',
      'is_mobile' => 'admin_user_sessions.is_mobile',
      'created' => 'admin_user_sessions.created',
    ),
    'names' => 
    array (
      'id' => 'id',
      'user_id' => 'user_id',
      'session_id' => 'session_id',
      'ip' => 'ip',
      'user_agent' => 'user_agent',
      'os' => 'os',
      'browser' => 'browser',
      'device_type' => 'device_type',
      'is_mobile' => 'is_mobile',
      'created' => 'created',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'user_id' => 'user_id',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'user_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'user_id',
         'name' => 'user_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'session_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'session_id',
         'name' => 'session_id',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 64,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'ip' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'ip',
         'name' => 'ip',
         'type' => 
        Colibri\Schema\Types\FloatType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'user_agent' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'user_agent',
         'name' => 'user_agent',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 255,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'os' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'os',
         'name' => 'os',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 32,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'browser' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'browser',
         'name' => 'browser',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 32,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'device_type' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'device_type',
         'name' => 'device_type',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 8,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'is_mobile' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'is_mobile',
         'name' => 'is_mobile',
         'type' => 
        Colibri\Schema\Types\BooleanType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'created' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'created',
         'name' => 'created',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
);