<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

return array (
  'ColibriLabs\\Database\\Om\\Movie' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\Movie',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\MovieRepository',
    'tableName' => 'movies',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'movies.id',
      'tmdb_id' => 'movies.tmdb_id',
      'imdb_id' => 'movies.imdb_id',
      'budget' => 'movies.budget',
      'revenue' => 'movies.revenue',
      'runtime' => 'movies.runtime',
      'release_date' => 'movies.release_date',
      'title' => 'movies.title',
      'soundex_title' => 'movies.soundex_title',
      'metaphone_title' => 'movies.metaphone_title',
      'original_title' => 'movies.original_title',
      'soundex_original_title' => 'movies.soundex_original_title',
      'metaphone_original_title' => 'movies.metaphone_original_title',
      'iso_language' => 'movies.iso_language',
      'overview' => 'movies.overview',
      'tagline' => 'movies.tagline',
      'tmdb_votes' => 'movies.tmdb_votes',
      'tmdb_rating' => 'movies.tmdb_rating',
      'imdb_votes' => 'movies.imdb_votes',
      'imdb_rating' => 'movies.imdb_rating',
      'mpaa_rating' => 'movies.mpaa_rating',
      'version' => 'movies.version',
      'created' => 'movies.created',
      'updated' => 'movies.updated',
    ),
    'names' => 
    array (
      'id' => 'id',
      'tmdb_id' => 'tmdb_id',
      'imdb_id' => 'imdb_id',
      'budget' => 'budget',
      'revenue' => 'revenue',
      'runtime' => 'runtime',
      'release_date' => 'release_date',
      'title' => 'title',
      'soundex_title' => 'soundex_title',
      'metaphone_title' => 'metaphone_title',
      'original_title' => 'original_title',
      'soundex_original_title' => 'soundex_original_title',
      'metaphone_original_title' => 'metaphone_original_title',
      'iso_language' => 'iso_language',
      'overview' => 'overview',
      'tagline' => 'tagline',
      'tmdb_votes' => 'tmdb_votes',
      'tmdb_rating' => 'tmdb_rating',
      'imdb_votes' => 'imdb_votes',
      'imdb_rating' => 'imdb_rating',
      'mpaa_rating' => 'mpaa_rating',
      'version' => 'version',
      'created' => 'created',
      'updated' => 'updated',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
      'mpaa_rating' => 
      array (
        0 => 'G',
        1 => 'PG',
        2 => 'PG-13',
        3 => 'R',
        4 => 'NC-17',
      ),
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'tmdb_id' => 'tmdb_id',
      'imdb_id' => 'imdb_id',
      'budget' => 'budget',
      'revenue' => 'revenue',
      'runtime' => 'runtime',
      'tmdb_votes' => 'tmdb_votes',
      'imdb_votes' => 'imdb_votes',
      'version' => 'version',
    ),
    'primary' => 
    array (
      'id' => 'id',
      'tmdb_id' => 'tmdb_id',
      'imdb_id' => 'imdb_id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'tmdb_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'tmdb_id',
         'name' => 'tmdb_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'imdb_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'imdb_id',
         'name' => 'imdb_id',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 9,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'budget' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'budget',
         'name' => 'budget',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'revenue' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'revenue',
         'name' => 'revenue',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'runtime' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'runtime',
         'name' => 'runtime',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'release_date' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'release_date',
         'name' => 'release_date',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'title' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'title',
         'name' => 'title',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 255,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'soundex_title' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'soundex_title',
         'name' => 'soundex_title',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 255,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'metaphone_title' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'metaphone_title',
         'name' => 'metaphone_title',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 255,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'original_title' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'original_title',
         'name' => 'original_title',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 255,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'soundex_original_title' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'soundex_original_title',
         'name' => 'soundex_original_title',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 255,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'metaphone_original_title' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'metaphone_original_title',
         'name' => 'metaphone_original_title',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 255,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'iso_language' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'iso_language',
         'name' => 'iso_language',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 2,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'overview' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'overview',
         'name' => 'overview',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'tagline' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'tagline',
         'name' => 'tagline',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'tmdb_votes' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'tmdb_votes',
         'name' => 'tmdb_votes',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'tmdb_rating' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'tmdb_rating',
         'name' => 'tmdb_rating',
         'type' => 
        Colibri\Schema\Types\FloatType::__set_state(array(
           'length' => 10,
           'precision' => 4,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'imdb_votes' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'imdb_votes',
         'name' => 'imdb_votes',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'imdb_rating' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'imdb_rating',
         'name' => 'imdb_rating',
         'type' => 
        Colibri\Schema\Types\FloatType::__set_state(array(
           'length' => 10,
           'precision' => 4,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'mpaa_rating' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'mpaa_rating',
         'name' => 'mpaa_rating',
         'type' => 
        Colibri\Schema\Types\EnumType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => 
          array (
            0 => 'G',
            1 => 'PG',
            2 => 'PG-13',
            3 => 'R',
            4 => 'NC-17',
          ),
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'version' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'version',
         'name' => 'version',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'created' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'created',
         'name' => 'created',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'updated' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'updated',
         'name' => 'updated',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\Backdrop' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\Backdrop',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\BackdropRepository',
    'tableName' => 'backdrops',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'backdrops.id',
      'picture_id' => 'backdrops.picture_id',
      'movie_id' => 'backdrops.movie_id',
    ),
    'names' => 
    array (
      'id' => 'id',
      'picture_id' => 'picture_id',
      'movie_id' => 'movie_id',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'picture_id' => 'picture_id',
      'movie_id' => 'movie_id',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'picture_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'picture_id',
         'name' => 'picture_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'movie_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'movie_id',
         'name' => 'movie_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\Poster' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\Poster',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\PosterRepository',
    'tableName' => 'posters',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'posters.id',
      'picture_id' => 'posters.picture_id',
      'movie_id' => 'posters.movie_id',
    ),
    'names' => 
    array (
      'id' => 'id',
      'picture_id' => 'picture_id',
      'movie_id' => 'movie_id',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'picture_id' => 'picture_id',
      'movie_id' => 'movie_id',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'picture_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'picture_id',
         'name' => 'picture_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'movie_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'movie_id',
         'name' => 'movie_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\Picture' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\Picture',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\PictureRepository',
    'tableName' => 'pictures',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'pictures.id',
      'height' => 'pictures.height',
      'width' => 'pictures.width',
      'file_path' => 'pictures.file_path',
      'tmdb_file_path' => 'pictures.tmdb_file_path',
      'iso_639_1' => 'pictures.iso_639_1',
      'version' => 'pictures.version',
      'created' => 'pictures.created',
      'updated' => 'pictures.updated',
    ),
    'names' => 
    array (
      'id' => 'id',
      'height' => 'height',
      'width' => 'width',
      'file_path' => 'file_path',
      'tmdb_file_path' => 'tmdb_file_path',
      'iso_639_1' => 'iso_639_1',
      'version' => 'version',
      'created' => 'created',
      'updated' => 'updated',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'height' => 'height',
      'width' => 'width',
      'version' => 'version',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'height' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'height',
         'name' => 'height',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'width' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'width',
         'name' => 'width',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'file_path' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'file_path',
         'name' => 'file_path',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 128,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'tmdb_file_path' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'tmdb_file_path',
         'name' => 'tmdb_file_path',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 64,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'iso_639_1' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'iso_639_1',
         'name' => 'iso_639_1',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 2,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'version' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'version',
         'name' => 'version',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'created' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'created',
         'name' => 'created',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'updated' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'updated',
         'name' => 'updated',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\User' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\User',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\UserRepository',
    'tableName' => 'admin_users',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'admin_users.id',
      'email' => 'admin_users.email',
      'settings' => 'admin_users.settings',
      'login' => 'admin_users.login',
      'password' => 'admin_users.password',
    ),
    'names' => 
    array (
      'id' => 'id',
      'email' => 'email',
      'settings' => 'settings',
      'login' => 'login',
      'password' => 'password',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'email' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'email',
         'name' => 'email',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 64,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'settings' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'settings',
         'name' => 'settings',
         'type' => 
        Colibri\Schema\Types\JsonType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'login' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'login',
         'name' => 'login',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 64,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'password' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'password',
         'name' => 'password',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 64,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
  'ColibriLabs\\Database\\Om\\UserSession' => 
  array (
    'entityClass' => 'ColibriLabs\\Database\\Om\\UserSession',
    'entityRepositoryClass' => 'ColibriLabs\\Database\\Om\\UserSessionRepository',
    'tableName' => 'admin_user_sessions',
    'identifier' => 'id',
    'rawSQLNames' => 
    array (
      'id' => 'admin_user_sessions.id',
      'user_id' => 'admin_user_sessions.user_id',
      'session_id' => 'admin_user_sessions.session_id',
      'ip' => 'admin_user_sessions.ip',
      'user_agent' => 'admin_user_sessions.user_agent',
      'os' => 'admin_user_sessions.os',
      'browser' => 'admin_user_sessions.browser',
      'device_type' => 'admin_user_sessions.device_type',
      'is_mobile' => 'admin_user_sessions.is_mobile',
      'created' => 'admin_user_sessions.created',
    ),
    'names' => 
    array (
      'id' => 'id',
      'user_id' => 'user_id',
      'session_id' => 'session_id',
      'ip' => 'ip',
      'user_agent' => 'user_agent',
      'os' => 'os',
      'browser' => 'browser',
      'device_type' => 'device_type',
      'is_mobile' => 'is_mobile',
      'created' => 'created',
    ),
    'relations' => 
    array (
    ),
    'enumerations' => 
    array (
    ),
    'default' => 
    array (
    ),
    'nullables' => 
    array (
    ),
    'unsigned' => 
    array (
      'id' => 'id',
      'user_id' => 'user_id',
    ),
    'primary' => 
    array (
      'id' => 'id',
    ),
    'instances' => 
    array (
      'id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'id',
         'name' => 'id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => true,
         'primaryKey' => true,
         'identity' => false,
      )),
      'user_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'user_id',
         'name' => 'user_id',
         'type' => 
        Colibri\Schema\Types\IntegerType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => true,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'session_id' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'session_id',
         'name' => 'session_id',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 64,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'ip' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'ip',
         'name' => 'ip',
         'type' => 
        Colibri\Schema\Types\FloatType::__set_state(array(
           'length' => 11,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'user_agent' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'user_agent',
         'name' => 'user_agent',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 255,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'os' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'os',
         'name' => 'os',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 32,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'browser' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'browser',
         'name' => 'browser',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 32,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'device_type' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'device_type',
         'name' => 'device_type',
         'type' => 
        Colibri\Schema\Types\StringType::__set_state(array(
           'length' => 8,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'is_mobile' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'is_mobile',
         'name' => 'is_mobile',
         'type' => 
        Colibri\Schema\Types\BooleanType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
      'created' => 
      Colibri\Schema\Field::__set_state(array(
         'column' => 'created',
         'name' => 'created',
         'type' => 
        Colibri\Schema\Types\DatetimeType::__set_state(array(
           'length' => 0,
           'precision' => 0,
           'extra' => NULL,
        )),
         'default' => NULL,
         'unsigned' => false,
         'nullable' => false,
         'autoIncrement' => false,
         'primaryKey' => false,
         'identity' => false,
      )),
    ),
  ),
);