<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class MovieLanguage extends Base\BaseMovieLanguage
{
  // ... write your custom code here
}