<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class MovieCountry extends Base\BaseMovieCountry
{
  // ... write your custom code here
}