<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class MovieRepository extends Base\BaseMovieRepository
{
  // ... write your custom code here
}