<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class MovieGenre extends Base\BaseMovieGenre
{
  // ... write your custom code here
}