<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class MovieGenreRepository extends Base\BaseMovieGenreRepository
{
  // ... write your custom code here
}