<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class MovieCountryRepository extends Base\BaseMovieCountryRepository
{
  // ... write your custom code here
}