<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class MovieCompanyRepository extends Base\BaseMovieCompanyRepository
{
  // ... write your custom code here
}