<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

/**
 * Class MovieRepository
 * @package ColibriLabs\Database\Om
 */
class MovieRepository extends Base\BaseMovieRepository
{
    
}