<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class MovieLanguageRepository extends Base\BaseMovieLanguageRepository
{
  // ... write your custom code here
}