<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class MovieCompany extends Base\BaseMovieCompany
{
  // ... write your custom code here
}