<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

use Behat\Transliterator\Transliterator;
use Colibri\Collection\ArrayCollection;
use Colibri\Core\Collection\EntityCollection;

/**
 * Class Movie
 * @package ColibriLabs\Database\Om
 */
class Movie extends Base\BaseMovie
{
  
  /**
   * @var MovieRepository
   */
  protected $repository;
  
  /**
   * @return string
   */
  public function getTitleSlug()
  {
    return Transliterator::urlize(Transliterator::utf8ToAscii($this->getTitle()));
  }
  
  /**
   * @return string|null
   */
  public function getPosterPicture()
  {
    //
    return $this->virtual->offsetExists('posterPicture')
      ? $this->virtual->offsetGet('posterPicture')
      : 'https://dummyimage.com/230x320/993d34/fff.png&text=lostDB';
  }
  
  /**
   * @return string|null
   */
  public function getBackdropPicture()
  {
    return $this->virtual->offsetGet('backdropPicture');
  }
  
  /**
   * @return MovieRepository
   */
  public function getRepository()
  {
    return $this->repository;
  }

  /**
   * @return string
   */
  public function getShortOverview()
  {
    $number   = 35;
    $words    = preg_split('/\s+/ui', $this->getOverview());
    $dots     = count($words) > $number ? '...' : null;
    $words    = array_slice($words, 0, $number);

    return implode(' ', $words) . $dots;
  }
  
  /**
   * @param MovieRepository $repository
   * @return $this
   */
  public function setRepository(MovieRepository $repository)
  {
    $this->repository = $repository;
    
    return $this;
  }
  
}