<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class PhotoRepository extends Base\BasePhotoRepository
{
  // ... write your custom code here
}