<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class PictureRepository extends Base\BasePictureRepository
{
  // ... write your custom code here
}