<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;
use ColibriLabs\Lib\Util\BaseConverter;
use ColibriLabs\Lib\Util\BigIntPack;

/**
 * Class Picture
 * @package ColibriLabs\Database\Om
 */
class Picture extends Base\BasePicture
{
  
  /**
   * @return string
   */
  public function getTmdbPicturePath()
  {
    return sprintf('https://image.tmdb.org/t/p/original%s', $this->getTmdbFilePath());
  }
  
  /**
   * @return int|string
   */
  public function getPictureHash()
  {
    $bigint = BigIntPack::pack($this->getId(), $this->getWidth(), $this->getHeight());
    
    return BaseConverter::instance()->encode($bigint);
  }
  
  public function getAbsolutePath($absolutePath)
  {
    return sprintf('%s/%s.jpg', $absolutePath, $this->getPictureHash());
  }
  
}