<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

/**
 * Class Picture
 * @package ColibriLabs\Database\Om
 */
class Picture extends Base\BasePicture
{
  
  /**
   * @return string
   */
  public function getTmdbPicturePath()
  {
    return sprintf('https://image.tmdb.org/t/p/original%s', $this->getTmdbFilePath());
  }
  
}