<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class PosterRepository extends Base\BasePosterRepository
{
  // ... write your custom code here
}