<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class ProfileRepository extends Base\BaseProfileRepository
{
  // ... write your custom code here
}