<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class UserSession extends Base\BaseUserSession
{
  // ... write your custom code here
}