<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om;

class UserSessionRepository extends Base\BaseUserSessionRepository
{
  // ... write your custom code here
}