<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om\Base;

use Colibri\Core\Entity;

/**
 * Entity class for representation table 'backdrops'
 */
class BaseBackdrop extends Entity
{

  const TABLE = 'backdrops';

  const ID = 'backdrops.id';
  const PICTURE_ID = 'backdrops.picture_id';
  const MOVIE_ID = 'backdrops.movie_id';
  const ID_KEY = 'id';
  const PICTURE_ID_KEY = 'picture_id';
  const MOVIE_ID_KEY = 'movie_id';
  
  /**
   * @var integer
   */
  public $id;
  
  /**
   * @var integer
   */
  public $pictureId;
  
  /**
   * @var integer
   */
  public $movieId;

  /**
   * @return integer
   */
  public function getId()
  {
    return $this->id;
  }

  /**
   * @return integer
   */
  public function getPictureId()
  {
    return $this->pictureId;
  }

  /**
   * @return integer
   */
  public function getMovieId()
  {
    return $this->movieId;
  }


  /**
   * @param integer $id
   * @return $this
   */
  public function setId($id)
  {
    $this->id = $id;

    return $this;
  }

  /**
   * @param integer $pictureId
   * @return $this
   */
  public function setPictureId($pictureId)
  {
    $this->pictureId = $pictureId;

    return $this;
  }

  /**
   * @param integer $movieId
   * @return $this
   */
  public function setMovieId($movieId)
  {
    $this->movieId = $movieId;

    return $this;
  }

}