<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om\Base;

use Colibri\Core\Entity;

/**
 * Entity class for representation table 'pictures'
 */
class BasePicture extends Entity
{

  const TABLE = 'pictures';

  const ID = 'pictures.id';
  const HEIGHT = 'pictures.height';
  const WIDTH = 'pictures.width';
  const FILE_PATH = 'pictures.file_path';
  const TMDB_FILE_PATH = 'pictures.tmdb_file_path';
  const ISO_639_1 = 'pictures.iso_639_1';
  const VERSION = 'pictures.version';
  const CREATED = 'pictures.created';
  const UPDATED = 'pictures.updated';
  const ID_KEY = 'id';
  const HEIGHT_KEY = 'height';
  const WIDTH_KEY = 'width';
  const FILE_PATH_KEY = 'file_path';
  const TMDB_FILE_PATH_KEY = 'tmdb_file_path';
  const ISO_639_1_KEY = 'iso_639_1';
  const VERSION_KEY = 'version';
  const CREATED_KEY = 'created';
  const UPDATED_KEY = 'updated';
  
  /**
   * @var integer
   */
  public $id;
  
  /**
   * @var integer
   */
  public $height;
  
  /**
   * @var integer
   */
  public $width;
  
  /**
   * @var string
   */
  public $filePath;
  
  /**
   * @var string
   */
  public $tmdbFilePath;
  
  /**
   * @var string
   */
  public $iso6391;
  
  /**
   * @var integer
   */
  public $version;
  
  /**
   * @var string
   */
  public $created;
  
  /**
   * @var string
   */
  public $updated;

  /**
   * @return integer
   */
  public function getId()
  {
    return $this->id;
  }

  /**
   * @return integer
   */
  public function getHeight()
  {
    return $this->height;
  }

  /**
   * @return integer
   */
  public function getWidth()
  {
    return $this->width;
  }

  /**
   * @return string
   */
  public function getFilePath()
  {
    return $this->filePath;
  }

  /**
   * @return string
   */
  public function getTmdbFilePath()
  {
    return $this->tmdbFilePath;
  }

  /**
   * @return string
   */
  public function getIso6391()
  {
    return $this->iso6391;
  }

  /**
   * @return integer
   */
  public function getVersion()
  {
    return $this->version;
  }

  /**
   * @return string
   */
  public function getCreated()
  {
    return $this->created;
  }

  /**
   * @return string
   */
  public function getUpdated()
  {
    return $this->updated;
  }


  /**
   * @param integer $id
   * @return $this
   */
  public function setId($id)
  {
    $this->id = $id;

    return $this;
  }

  /**
   * @param integer $height
   * @return $this
   */
  public function setHeight($height)
  {
    $this->height = $height;

    return $this;
  }

  /**
   * @param integer $width
   * @return $this
   */
  public function setWidth($width)
  {
    $this->width = $width;

    return $this;
  }

  /**
   * @param string $filePath
   * @return $this
   */
  public function setFilePath($filePath)
  {
    $this->filePath = $filePath;

    return $this;
  }

  /**
   * @param string $tmdbFilePath
   * @return $this
   */
  public function setTmdbFilePath($tmdbFilePath)
  {
    $this->tmdbFilePath = $tmdbFilePath;

    return $this;
  }

  /**
   * @param string $iso6391
   * @return $this
   */
  public function setIso6391($iso6391)
  {
    $this->iso6391 = $iso6391;

    return $this;
  }

  /**
   * @param integer $version
   * @return $this
   */
  public function setVersion($version)
  {
    $this->version = $version;

    return $this;
  }

  /**
   * @param string $created
   * @return $this
   */
  public function setCreated($created)
  {
    $this->created = $created;

    return $this;
  }

  /**
   * @param string $updated
   * @return $this
   */
  public function setUpdated($updated)
  {
    $this->updated = $updated;

    return $this;
  }

}