<?php
/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om\Base;

use Colibri\Core\Repository;
use Colibri\Query\Statement\Comparison\Cmp;
use Colibri\Query\Statement\OrderBy;
use ColibriLabs\Database\Om\GenreRepository;
use ColibriLabs\Database\Om\Genre;
use Colibri\Core\ResultSet\ResultSetIterator;

/**
 * Magic methods for query-builder and access to the fields data
 *
 * @method Genre findOneById($id);
 * @method ResultSetIterator findById($id);
 * @method GenreRepository filterById($id, $cmp = Cmp::EQ);
 * @method GenreRepository orderById($vector = OrderBy::ASC);
 * @method GenreRepository groupById();
 * @method Genre findOneByTmdbId($tmdb_id);
 * @method ResultSetIterator findByTmdbId($tmdb_id);
 * @method GenreRepository filterByTmdbId($tmdb_id, $cmp = Cmp::EQ);
 * @method GenreRepository orderByTmdbId($vector = OrderBy::ASC);
 * @method GenreRepository groupByTmdbId();
 * @method Genre findOneByName($name);
 * @method ResultSetIterator findByName($name);
 * @method GenreRepository filterByName($name, $cmp = Cmp::EQ);
 * @method GenreRepository orderByName($vector = OrderBy::ASC);
 * @method GenreRepository groupByName();
 * @method Genre findOneByVersion($version);
 * @method ResultSetIterator findByVersion($version);
 * @method GenreRepository filterByVersion($version, $cmp = Cmp::EQ);
 * @method GenreRepository orderByVersion($vector = OrderBy::ASC);
 * @method GenreRepository groupByVersion();
 * @method Genre findOneByCreated($created);
 * @method ResultSetIterator findByCreated($created);
 * @method GenreRepository filterByCreated($created, $cmp = Cmp::EQ);
 * @method GenreRepository orderByCreated($vector = OrderBy::ASC);
 * @method GenreRepository groupByCreated();
 * @method Genre findOneByUpdated($updated);
 * @method ResultSetIterator findByUpdated($updated);
 * @method GenreRepository filterByUpdated($updated, $cmp = Cmp::EQ);
 * @method GenreRepository orderByUpdated($vector = OrderBy::ASC);
 * @method GenreRepository groupByUpdated();
*/

class BaseGenreRepository extends Repository
{
  
  /**
   * BaseGenreRepository constructor.
   */
  public function __construct()
  {
    parent::__construct(Genre::class);
  }

}