<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om\Base;

use Colibri\Core\Entity;

/**
 * Entity class for representation table 'photos'
 */
class BasePhoto extends Entity
{

  const TABLE = 'photos';

  const ID = 'photos.id';
  const PICTURE_ID = 'photos.picture_id';
  const PROFILE_ID = 'photos.profile_id';
  const ID_KEY = 'id';
  const PICTURE_ID_KEY = 'picture_id';
  const PROFILE_ID_KEY = 'profile_id';
  
  /**
   * @var integer
   */
  public $id;
  
  /**
   * @var integer
   */
  public $pictureId;
  
  /**
   * @var integer
   */
  public $profileId;

  /**
   * @return integer
   */
  public function getId()
  {
    return $this->id;
  }

  /**
   * @return integer
   */
  public function getPictureId()
  {
    return $this->pictureId;
  }

  /**
   * @return integer
   */
  public function getProfileId()
  {
    return $this->profileId;
  }


  /**
   * @param integer $id
   * @return $this
   */
  public function setId($id)
  {
    $this->id = $id;

    return $this;
  }

  /**
   * @param integer $pictureId
   * @return $this
   */
  public function setPictureId($pictureId)
  {
    $this->pictureId = $pictureId;

    return $this;
  }

  /**
   * @param integer $profileId
   * @return $this
   */
  public function setProfileId($profileId)
  {
    $this->profileId = $profileId;

    return $this;
  }

}