<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om\Base;

use Colibri\Core\Entity;

/**
 * Entity class for representation table 'movie_country'
 */
class BaseMovieCountry extends Entity
{

  const TABLE = 'movie_country';

  const ID = 'movie_country.id';
  const MOVIE_ID = 'movie_country.movie_id';
  const COUNTRY_ID = 'movie_country.country_id';
  const ID_KEY = 'id';
  const MOVIE_ID_KEY = 'movie_id';
  const COUNTRY_ID_KEY = 'country_id';
  
  /**
   * @var integer
   */
  public $id;
  
  /**
   * @var integer
   */
  public $movieId;
  
  /**
   * @var integer
   */
  public $countryId;

  /**
   * @return integer
   */
  public function getId()
  {
    return $this->id;
  }

  /**
   * @return integer
   */
  public function getMovieId()
  {
    return $this->movieId;
  }

  /**
   * @return integer
   */
  public function getCountryId()
  {
    return $this->countryId;
  }


  /**
   * @param integer $id
   * @return $this
   */
  public function setId($id)
  {
    $this->id = $id;

    return $this;
  }

  /**
   * @param integer $movieId
   * @return $this
   */
  public function setMovieId($movieId)
  {
    $this->movieId = $movieId;

    return $this;
  }

  /**
   * @param integer $countryId
   * @return $this
   */
  public function setCountryId($countryId)
  {
    $this->countryId = $countryId;

    return $this;
  }

}