<?php
/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om\Base;

use Colibri\Core\Repository;
use Colibri\Query\Statement\Comparison\Cmp;
use Colibri\Query\Statement\OrderBy;
use ColibriLabs\Database\Om\CollectionPosterRepository;
use ColibriLabs\Database\Om\CollectionPoster;
use Colibri\Core\ResultSet\ResultSetIterator;

/**
 * Magic methods for query-builder and access to the fields data
 *
 * @method CollectionPoster findOneById($id);
 * @method ResultSetIterator findById($id);
 * @method CollectionPosterRepository filterById($id, $cmp = Cmp::EQ);
 * @method CollectionPosterRepository orderById($vector = OrderBy::ASC);
 * @method CollectionPosterRepository groupById();
 * @method CollectionPoster findOneByPictureId($picture_id);
 * @method ResultSetIterator findByPictureId($picture_id);
 * @method CollectionPosterRepository filterByPictureId($picture_id, $cmp = Cmp::EQ);
 * @method CollectionPosterRepository orderByPictureId($vector = OrderBy::ASC);
 * @method CollectionPosterRepository groupByPictureId();
 * @method CollectionPoster findOneByCollectionId($collection_id);
 * @method ResultSetIterator findByCollectionId($collection_id);
 * @method CollectionPosterRepository filterByCollectionId($collection_id, $cmp = Cmp::EQ);
 * @method CollectionPosterRepository orderByCollectionId($vector = OrderBy::ASC);
 * @method CollectionPosterRepository groupByCollectionId();
*/

class BaseCollectionPosterRepository extends Repository
{
  
  /**
   * BaseCollectionPosterRepository constructor.
   */
  public function __construct()
  {
    parent::__construct(CollectionPoster::class);
  }

}