<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om\Base;

use Colibri\Core\Entity;

/**
 * Entity class for representation table 'admin_users'
 */
class BaseUser extends Entity
{

  const TABLE = 'admin_users';

  const ID = 'admin_users.id';
  const EMAIL = 'admin_users.email';
  const SETTINGS = 'admin_users.settings';
  const LOGIN = 'admin_users.login';
  const PASSWORD = 'admin_users.password';
  const ID_KEY = 'id';
  const EMAIL_KEY = 'email';
  const SETTINGS_KEY = 'settings';
  const LOGIN_KEY = 'login';
  const PASSWORD_KEY = 'password';
  
  /**
   * @var integer
   */
  public $id;
  
  /**
   * @var string
   */
  public $email;
  
  /**
   * @var string
   */
  public $settings;
  
  /**
   * @var string
   */
  public $login;
  
  /**
   * @var string
   */
  public $password;

  /**
   * @return integer
   */
  public function getId()
  {
    return $this->id;
  }

  /**
   * @return string
   */
  public function getEmail()
  {
    return $this->email;
  }

  /**
   * @return string
   */
  public function getSettings()
  {
    return $this->settings;
  }

  /**
   * @return string
   */
  public function getLogin()
  {
    return $this->login;
  }

  /**
   * @return string
   */
  public function getPassword()
  {
    return $this->password;
  }


  /**
   * @param integer $id
   * @return $this
   */
  public function setId($id)
  {
    $this->id = $id;

    return $this;
  }

  /**
   * @param string $email
   * @return $this
   */
  public function setEmail($email)
  {
    $this->email = $email;

    return $this;
  }

  /**
   * @param string $settings
   * @return $this
   */
  public function setSettings($settings)
  {
    $this->settings = $settings;

    return $this;
  }

  /**
   * @param string $login
   * @return $this
   */
  public function setLogin($login)
  {
    $this->login = $login;

    return $this;
  }

  /**
   * @param string $password
   * @return $this
   */
  public function setPassword($password)
  {
    $this->password = $password;

    return $this;
  }

}