<?php
/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om\Base;

use Colibri\Core\Repository;
use Colibri\Query\Statement\Comparison\Cmp;
use Colibri\Query\Statement\OrderBy;
use ColibriLabs\Database\Om\MovieCountryRepository;
use ColibriLabs\Database\Om\MovieCountry;
use Colibri\Core\ResultSet\ResultSetIterator;

/**
 * Magic methods for query-builder and access to the fields data
 *
 * @method MovieCountry findOneById($id);
 * @method ResultSetIterator findById($id);
 * @method MovieCountryRepository filterById($id, $cmp = Cmp::EQ);
 * @method MovieCountryRepository orderById($vector = OrderBy::ASC);
 * @method MovieCountryRepository groupById();
 * @method MovieCountry findOneByMovieId($movie_id);
 * @method ResultSetIterator findByMovieId($movie_id);
 * @method MovieCountryRepository filterByMovieId($movie_id, $cmp = Cmp::EQ);
 * @method MovieCountryRepository orderByMovieId($vector = OrderBy::ASC);
 * @method MovieCountryRepository groupByMovieId();
 * @method MovieCountry findOneByCountryId($country_id);
 * @method ResultSetIterator findByCountryId($country_id);
 * @method MovieCountryRepository filterByCountryId($country_id, $cmp = Cmp::EQ);
 * @method MovieCountryRepository orderByCountryId($vector = OrderBy::ASC);
 * @method MovieCountryRepository groupByCountryId();
*/

class BaseMovieCountryRepository extends Repository
{
  
  /**
   * BaseMovieCountryRepository constructor.
   */
  public function __construct()
  {
    parent::__construct(MovieCountry::class);
  }

}