<?php
/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om\Base;

use Colibri\Core\Repository;
use Colibri\Query\Statement\Comparison\Cmp;
use Colibri\Query\Statement\OrderBy;
use ColibriLabs\Database\Om\CollectionBackdropRepository;
use ColibriLabs\Database\Om\CollectionBackdrop;
use Colibri\Core\ResultSet\ResultSetIterator;

/**
 * Magic methods for query-builder and access to the fields data
 *
 * @method CollectionBackdrop findOneById($id);
 * @method ResultSetIterator findById($id);
 * @method CollectionBackdropRepository filterById($id, $cmp = Cmp::EQ);
 * @method CollectionBackdropRepository orderById($vector = OrderBy::ASC);
 * @method CollectionBackdropRepository groupById();
 * @method CollectionBackdrop findOneByPictureId($picture_id);
 * @method ResultSetIterator findByPictureId($picture_id);
 * @method CollectionBackdropRepository filterByPictureId($picture_id, $cmp = Cmp::EQ);
 * @method CollectionBackdropRepository orderByPictureId($vector = OrderBy::ASC);
 * @method CollectionBackdropRepository groupByPictureId();
 * @method CollectionBackdrop findOneByCollectionId($collection_id);
 * @method ResultSetIterator findByCollectionId($collection_id);
 * @method CollectionBackdropRepository filterByCollectionId($collection_id, $cmp = Cmp::EQ);
 * @method CollectionBackdropRepository orderByCollectionId($vector = OrderBy::ASC);
 * @method CollectionBackdropRepository groupByCollectionId();
*/

class BaseCollectionBackdropRepository extends Repository
{
  
  /**
   * BaseCollectionBackdropRepository constructor.
   */
  public function __construct()
  {
    parent::__construct(CollectionBackdrop::class);
  }

}