<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om\Base;

use Colibri\Core\Entity;

/**
 * Entity class for representation table 'admin_user_sessions'
 */
class BaseUserSession extends Entity
{

  const TABLE = 'admin_user_sessions';

  const ID = 'admin_user_sessions.id';
  const USER_ID = 'admin_user_sessions.user_id';
  const SESSION_ID = 'admin_user_sessions.session_id';
  const IP = 'admin_user_sessions.ip';
  const USER_AGENT = 'admin_user_sessions.user_agent';
  const OS = 'admin_user_sessions.os';
  const BROWSER = 'admin_user_sessions.browser';
  const DEVICE_TYPE = 'admin_user_sessions.device_type';
  const IS_MOBILE = 'admin_user_sessions.is_mobile';
  const CREATED = 'admin_user_sessions.created';
  const ID_KEY = 'id';
  const USER_ID_KEY = 'user_id';
  const SESSION_ID_KEY = 'session_id';
  const IP_KEY = 'ip';
  const USER_AGENT_KEY = 'user_agent';
  const OS_KEY = 'os';
  const BROWSER_KEY = 'browser';
  const DEVICE_TYPE_KEY = 'device_type';
  const IS_MOBILE_KEY = 'is_mobile';
  const CREATED_KEY = 'created';
  
  /**
   * @var integer
   */
  public $id;
  
  /**
   * @var integer
   */
  public $userId;
  
  /**
   * @var string
   */
  public $sessionId;
  
  /**
   * @var float
   */
  public $ip;
  
  /**
   * @var string
   */
  public $userAgent;
  
  /**
   * @var string
   */
  public $os;
  
  /**
   * @var string
   */
  public $browser;
  
  /**
   * @var string
   */
  public $deviceType;
  
  /**
   * @var boolean
   */
  public $isMobile;
  
  /**
   * @var string
   */
  public $created;

  /**
   * @return integer
   */
  public function getId()
  {
    return $this->id;
  }

  /**
   * @return integer
   */
  public function getUserId()
  {
    return $this->userId;
  }

  /**
   * @return string
   */
  public function getSessionId()
  {
    return $this->sessionId;
  }

  /**
   * @return float
   */
  public function getIp()
  {
    return $this->ip;
  }

  /**
   * @return string
   */
  public function getUserAgent()
  {
    return $this->userAgent;
  }

  /**
   * @return string
   */
  public function getOs()
  {
    return $this->os;
  }

  /**
   * @return string
   */
  public function getBrowser()
  {
    return $this->browser;
  }

  /**
   * @return string
   */
  public function getDeviceType()
  {
    return $this->deviceType;
  }

  /**
   * @return boolean
   */
  public function getIsMobile()
  {
    return $this->isMobile;
  }

  /**
   * @return string
   */
  public function getCreated()
  {
    return $this->created;
  }


  /**
   * @param integer $id
   * @return $this
   */
  public function setId($id)
  {
    $this->id = $id;

    return $this;
  }

  /**
   * @param integer $userId
   * @return $this
   */
  public function setUserId($userId)
  {
    $this->userId = $userId;

    return $this;
  }

  /**
   * @param string $sessionId
   * @return $this
   */
  public function setSessionId($sessionId)
  {
    $this->sessionId = $sessionId;

    return $this;
  }

  /**
   * @param float $ip
   * @return $this
   */
  public function setIp($ip)
  {
    $this->ip = $ip;

    return $this;
  }

  /**
   * @param string $userAgent
   * @return $this
   */
  public function setUserAgent($userAgent)
  {
    $this->userAgent = $userAgent;

    return $this;
  }

  /**
   * @param string $os
   * @return $this
   */
  public function setOs($os)
  {
    $this->os = $os;

    return $this;
  }

  /**
   * @param string $browser
   * @return $this
   */
  public function setBrowser($browser)
  {
    $this->browser = $browser;

    return $this;
  }

  /**
   * @param string $deviceType
   * @return $this
   */
  public function setDeviceType($deviceType)
  {
    $this->deviceType = $deviceType;

    return $this;
  }

  /**
   * @param boolean $isMobile
   * @return $this
   */
  public function setIsMobile($isMobile)
  {
    $this->isMobile = $isMobile;

    return $this;
  }

  /**
   * @param string $created
   * @return $this
   */
  public function setCreated($created)
  {
    $this->created = $created;

    return $this;
  }

}