<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om\Base;

use Colibri\Core\Entity;

/**
 * Entity class for representation table 'movie_language'
 */
class BaseMovieLanguage extends Entity
{

  const TABLE = 'movie_language';

  const ID = 'movie_language.id';
  const MOVIE_ID = 'movie_language.movie_id';
  const LANGUAGE_ID = 'movie_language.language_id';
  const ID_KEY = 'id';
  const MOVIE_ID_KEY = 'movie_id';
  const LANGUAGE_ID_KEY = 'language_id';
  
  /**
   * @var integer
   */
  public $id;
  
  /**
   * @var integer
   */
  public $movieId;
  
  /**
   * @var integer
   */
  public $languageId;

  /**
   * @return integer
   */
  public function getId()
  {
    return $this->id;
  }

  /**
   * @return integer
   */
  public function getMovieId()
  {
    return $this->movieId;
  }

  /**
   * @return integer
   */
  public function getLanguageId()
  {
    return $this->languageId;
  }


  /**
   * @param integer $id
   * @return $this
   */
  public function setId($id)
  {
    $this->id = $id;

    return $this;
  }

  /**
   * @param integer $movieId
   * @return $this
   */
  public function setMovieId($movieId)
  {
    $this->movieId = $movieId;

    return $this;
  }

  /**
   * @param integer $languageId
   * @return $this
   */
  public function setLanguageId($languageId)
  {
    $this->languageId = $languageId;

    return $this;
  }

}