<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om\Base;

use Colibri\Core\Entity;

/**
 * Entity class for representation table 'crews'
 */
class BaseCrew extends Entity
{

  const TABLE = 'crews';

  const ID = 'crews.id';
  const PROFILE_ID = 'crews.profile_id';
  const MOVIE_ID = 'crews.movie_id';
  const DEPARTMENT = 'crews.department';
  const JOB = 'crews.job';
  const VERSION = 'crews.version';
  const CREATED = 'crews.created';
  const UPDATED = 'crews.updated';
  const ID_KEY = 'id';
  const PROFILE_ID_KEY = 'profile_id';
  const MOVIE_ID_KEY = 'movie_id';
  const DEPARTMENT_KEY = 'department';
  const JOB_KEY = 'job';
  const VERSION_KEY = 'version';
  const CREATED_KEY = 'created';
  const UPDATED_KEY = 'updated';
  
  /**
   * @var integer
   */
  public $id;
  
  /**
   * @var integer
   */
  public $profileId;
  
  /**
   * @var integer
   */
  public $movieId;
  
  /**
   * @var string
   */
  public $department;
  
  /**
   * @var string
   */
  public $job;
  
  /**
   * @var integer
   */
  public $version;
  
  /**
   * @var string
   */
  public $created;
  
  /**
   * @var string
   */
  public $updated;

  /**
   * @return integer
   */
  public function getId()
  {
    return $this->id;
  }

  /**
   * @return integer
   */
  public function getProfileId()
  {
    return $this->profileId;
  }

  /**
   * @return integer
   */
  public function getMovieId()
  {
    return $this->movieId;
  }

  /**
   * @return string
   */
  public function getDepartment()
  {
    return $this->department;
  }

  /**
   * @return string
   */
  public function getJob()
  {
    return $this->job;
  }

  /**
   * @return integer
   */
  public function getVersion()
  {
    return $this->version;
  }

  /**
   * @return string
   */
  public function getCreated()
  {
    return $this->created;
  }

  /**
   * @return string
   */
  public function getUpdated()
  {
    return $this->updated;
  }


  /**
   * @param integer $id
   * @return $this
   */
  public function setId($id)
  {
    $this->id = $id;

    return $this;
  }

  /**
   * @param integer $profileId
   * @return $this
   */
  public function setProfileId($profileId)
  {
    $this->profileId = $profileId;

    return $this;
  }

  /**
   * @param integer $movieId
   * @return $this
   */
  public function setMovieId($movieId)
  {
    $this->movieId = $movieId;

    return $this;
  }

  /**
   * @param string $department
   * @return $this
   */
  public function setDepartment($department)
  {
    $this->department = $department;

    return $this;
  }

  /**
   * @param string $job
   * @return $this
   */
  public function setJob($job)
  {
    $this->job = $job;

    return $this;
  }

  /**
   * @param integer $version
   * @return $this
   */
  public function setVersion($version)
  {
    $this->version = $version;

    return $this;
  }

  /**
   * @param string $created
   * @return $this
   */
  public function setCreated($created)
  {
    $this->created = $created;

    return $this;
  }

  /**
   * @param string $updated
   * @return $this
   */
  public function setUpdated($updated)
  {
    $this->updated = $updated;

    return $this;
  }

}