<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om\Base;

use Colibri\Core\Entity;

/**
 * Entity class for representation table 'movie_company'
 */
class BaseMovieCompany extends Entity
{

  const TABLE = 'movie_company';

  const ID = 'movie_company.id';
  const MOVIE_ID = 'movie_company.movie_id';
  const COMPANY_ID = 'movie_company.company_id';
  const ID_KEY = 'id';
  const MOVIE_ID_KEY = 'movie_id';
  const COMPANY_ID_KEY = 'company_id';
  
  /**
   * @var integer
   */
  public $id;
  
  /**
   * @var integer
   */
  public $movieId;
  
  /**
   * @var integer
   */
  public $companyId;

  /**
   * @return integer
   */
  public function getId()
  {
    return $this->id;
  }

  /**
   * @return integer
   */
  public function getMovieId()
  {
    return $this->movieId;
  }

  /**
   * @return integer
   */
  public function getCompanyId()
  {
    return $this->companyId;
  }


  /**
   * @param integer $id
   * @return $this
   */
  public function setId($id)
  {
    $this->id = $id;

    return $this;
  }

  /**
   * @param integer $movieId
   * @return $this
   */
  public function setMovieId($movieId)
  {
    $this->movieId = $movieId;

    return $this;
  }

  /**
   * @param integer $companyId
   * @return $this
   */
  public function setCompanyId($companyId)
  {
    $this->companyId = $companyId;

    return $this;
  }

}