<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om\Base;

use Colibri\Core\Entity;

/**
 * Entity class for representation table 'collection_posters'
 */
class BaseCollectionPoster extends Entity
{

  const TABLE = 'collection_posters';

  const ID = 'collection_posters.id';
  const PICTURE_ID = 'collection_posters.picture_id';
  const COLLECTION_ID = 'collection_posters.collection_id';
  const ID_KEY = 'id';
  const PICTURE_ID_KEY = 'picture_id';
  const COLLECTION_ID_KEY = 'collection_id';
  
  /**
   * @var integer
   */
  public $id;
  
  /**
   * @var integer
   */
  public $pictureId;
  
  /**
   * @var integer
   */
  public $collectionId;

  /**
   * @return integer
   */
  public function getId()
  {
    return $this->id;
  }

  /**
   * @return integer
   */
  public function getPictureId()
  {
    return $this->pictureId;
  }

  /**
   * @return integer
   */
  public function getCollectionId()
  {
    return $this->collectionId;
  }


  /**
   * @param integer $id
   * @return $this
   */
  public function setId($id)
  {
    $this->id = $id;

    return $this;
  }

  /**
   * @param integer $pictureId
   * @return $this
   */
  public function setPictureId($pictureId)
  {
    $this->pictureId = $pictureId;

    return $this;
  }

  /**
   * @param integer $collectionId
   * @return $this
   */
  public function setCollectionId($collectionId)
  {
    $this->collectionId = $collectionId;

    return $this;
  }

}