<?php
/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om\Base;

use Colibri\Core\Repository;
use Colibri\Query\Statement\Comparison\Cmp;
use Colibri\Query\Statement\OrderBy;
use ColibriLabs\Database\Om\MovieCompanyRepository;
use ColibriLabs\Database\Om\MovieCompany;
use Colibri\Core\ResultSet\ResultSetIterator;

/**
 * Magic methods for query-builder and access to the fields data
 *
 * @method MovieCompany findOneById($id);
 * @method ResultSetIterator findById($id);
 * @method MovieCompanyRepository filterById($id, $cmp = Cmp::EQ);
 * @method MovieCompanyRepository orderById($vector = OrderBy::ASC);
 * @method MovieCompanyRepository groupById();
 * @method MovieCompany findOneByMovieId($movie_id);
 * @method ResultSetIterator findByMovieId($movie_id);
 * @method MovieCompanyRepository filterByMovieId($movie_id, $cmp = Cmp::EQ);
 * @method MovieCompanyRepository orderByMovieId($vector = OrderBy::ASC);
 * @method MovieCompanyRepository groupByMovieId();
 * @method MovieCompany findOneByCompanyId($company_id);
 * @method ResultSetIterator findByCompanyId($company_id);
 * @method MovieCompanyRepository filterByCompanyId($company_id, $cmp = Cmp::EQ);
 * @method MovieCompanyRepository orderByCompanyId($vector = OrderBy::ASC);
 * @method MovieCompanyRepository groupByCompanyId();
*/

class BaseMovieCompanyRepository extends Repository
{
  
  /**
   * BaseMovieCompanyRepository constructor.
   */
  public function __construct()
  {
    parent::__construct(MovieCompany::class);
  }

}