<?php
/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om\Base;

use Colibri\Core\Repository;
use Colibri\Query\Statement\Comparison\Cmp;
use Colibri\Query\Statement\OrderBy;
use ColibriLabs\Database\Om\BackdropRepository;
use ColibriLabs\Database\Om\Backdrop;
use Colibri\Core\ResultSet\ResultSetIterator;

/**
 * Magic methods for query-builder and access to the fields data
 *
 * @method Backdrop findOneById($id);
 * @method ResultSetIterator findById($id);
 * @method BackdropRepository filterById($id, $cmp = Cmp::EQ);
 * @method BackdropRepository orderById($vector = OrderBy::ASC);
 * @method BackdropRepository groupById();
 * @method Backdrop findOneByPictureId($picture_id);
 * @method ResultSetIterator findByPictureId($picture_id);
 * @method BackdropRepository filterByPictureId($picture_id, $cmp = Cmp::EQ);
 * @method BackdropRepository orderByPictureId($vector = OrderBy::ASC);
 * @method BackdropRepository groupByPictureId();
 * @method Backdrop findOneByMovieId($movie_id);
 * @method ResultSetIterator findByMovieId($movie_id);
 * @method BackdropRepository filterByMovieId($movie_id, $cmp = Cmp::EQ);
 * @method BackdropRepository orderByMovieId($vector = OrderBy::ASC);
 * @method BackdropRepository groupByMovieId();
*/

class BaseBackdropRepository extends Repository
{
  
  /**
   * BaseBackdropRepository constructor.
   */
  public function __construct()
  {
    parent::__construct(Backdrop::class);
  }

}