<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om\Base;

use Colibri\Core\Entity;

/**
 * Entity class for representation table 'profiles'
 */
class BaseProfile extends Entity
{

  const TABLE = 'profiles';

  const ID = 'profiles.id';
  const TMDB_ID = 'profiles.tmdb_id';
  const IMDB_ID = 'profiles.imdb_id';
  const NAME = 'profiles.name';
  const BIOGRAPHY = 'profiles.biography';
  const ADULT = 'profiles.adult';
  const SEX = 'profiles.sex';
  const BIRTHDAY = 'profiles.birthday';
  const DEATHDAY = 'profiles.deathday';
  const VERSION = 'profiles.version';
  const CREATED = 'profiles.created';
  const UPDATED = 'profiles.updated';
  const ID_KEY = 'id';
  const TMDB_ID_KEY = 'tmdb_id';
  const IMDB_ID_KEY = 'imdb_id';
  const NAME_KEY = 'name';
  const BIOGRAPHY_KEY = 'biography';
  const ADULT_KEY = 'adult';
  const SEX_KEY = 'sex';
  const BIRTHDAY_KEY = 'birthday';
  const DEATHDAY_KEY = 'deathday';
  const VERSION_KEY = 'version';
  const CREATED_KEY = 'created';
  const UPDATED_KEY = 'updated';
  const ENUM_SEX_F = 'F';
  const ENUM_SEX_M = 'M';
  
  /**
   * @var integer
   */
  public $id;
  
  /**
   * @var integer
   */
  public $tmdbId;
  
  /**
   * @var string
   */
  public $imdbId;
  
  /**
   * @var string
   */
  public $name;
  
  /**
   * @var string
   */
  public $biography;
  
  /**
   * @var boolean
   */
  public $adult;
  
  /**
   * @var string
   */
  public $sex;
  
  /**
   * @var string
   */
  public $birthday;
  
  /**
   * @var string
   */
  public $deathday;
  
  /**
   * @var integer
   */
  public $version;
  
  /**
   * @var string
   */
  public $created;
  
  /**
   * @var string
   */
  public $updated;

  /**
   * @return integer
   */
  public function getId()
  {
    return $this->id;
  }

  /**
   * @return integer
   */
  public function getTmdbId()
  {
    return $this->tmdbId;
  }

  /**
   * @return string
   */
  public function getImdbId()
  {
    return $this->imdbId;
  }

  /**
   * @return string
   */
  public function getName()
  {
    return $this->name;
  }

  /**
   * @return string
   */
  public function getBiography()
  {
    return $this->biography;
  }

  /**
   * @return boolean
   */
  public function getAdult()
  {
    return $this->adult;
  }

  /**
   * @return string
   */
  public function getSex()
  {
    return $this->sex;
  }

  /**
   * @return string
   */
  public function getBirthday()
  {
    return $this->birthday;
  }

  /**
   * @return string
   */
  public function getDeathday()
  {
    return $this->deathday;
  }

  /**
   * @return integer
   */
  public function getVersion()
  {
    return $this->version;
  }

  /**
   * @return string
   */
  public function getCreated()
  {
    return $this->created;
  }

  /**
   * @return string
   */
  public function getUpdated()
  {
    return $this->updated;
  }


  /**
   * @param integer $id
   * @return $this
   */
  public function setId($id)
  {
    $this->id = $id;

    return $this;
  }

  /**
   * @param integer $tmdbId
   * @return $this
   */
  public function setTmdbId($tmdbId)
  {
    $this->tmdbId = $tmdbId;

    return $this;
  }

  /**
   * @param string $imdbId
   * @return $this
   */
  public function setImdbId($imdbId)
  {
    $this->imdbId = $imdbId;

    return $this;
  }

  /**
   * @param string $name
   * @return $this
   */
  public function setName($name)
  {
    $this->name = $name;

    return $this;
  }

  /**
   * @param string $biography
   * @return $this
   */
  public function setBiography($biography)
  {
    $this->biography = $biography;

    return $this;
  }

  /**
   * @param boolean $adult
   * @return $this
   */
  public function setAdult($adult)
  {
    $this->adult = $adult;

    return $this;
  }

  /**
   * @param string $sex
   * @return $this
   */
  public function setSex($sex)
  {
    $this->sex = $sex;

    return $this;
  }

  /**
   * @param string $birthday
   * @return $this
   */
  public function setBirthday($birthday)
  {
    $this->birthday = $birthday;

    return $this;
  }

  /**
   * @param string $deathday
   * @return $this
   */
  public function setDeathday($deathday)
  {
    $this->deathday = $deathday;

    return $this;
  }

  /**
   * @param integer $version
   * @return $this
   */
  public function setVersion($version)
  {
    $this->version = $version;

    return $this;
  }

  /**
   * @param string $created
   * @return $this
   */
  public function setCreated($created)
  {
    $this->created = $created;

    return $this;
  }

  /**
   * @param string $updated
   * @return $this
   */
  public function setUpdated($updated)
  {
    $this->updated = $updated;

    return $this;
  }

}