<?php
/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ColibriLabs\Database\Om\Base;

use Colibri\Core\Repository;
use Colibri\Query\Statement\Comparison\Cmp;
use Colibri\Query\Statement\OrderBy;
use ColibriLabs\Database\Om\PhotoRepository;
use ColibriLabs\Database\Om\Photo;
use Colibri\Core\ResultSet\ResultSetIterator;

/**
 * Magic methods for query-builder and access to the fields data
 *
 * @method Photo findOneById($id);
 * @method ResultSetIterator findById($id);
 * @method PhotoRepository filterById($id, $cmp = Cmp::EQ);
 * @method PhotoRepository orderById($vector = OrderBy::ASC);
 * @method PhotoRepository groupById();
 * @method Photo findOneByPictureId($picture_id);
 * @method ResultSetIterator findByPictureId($picture_id);
 * @method PhotoRepository filterByPictureId($picture_id, $cmp = Cmp::EQ);
 * @method PhotoRepository orderByPictureId($vector = OrderBy::ASC);
 * @method PhotoRepository groupByPictureId();
 * @method Photo findOneByProfileId($profile_id);
 * @method ResultSetIterator findByProfileId($profile_id);
 * @method PhotoRepository filterByProfileId($profile_id, $cmp = Cmp::EQ);
 * @method PhotoRepository orderByProfileId($vector = OrderBy::ASC);
 * @method PhotoRepository groupByProfileId();
*/

class BasePhotoRepository extends Repository
{
  
  /**
   * BasePhotoRepository constructor.
   */
  public function __construct()
  {
    parent::__construct(Photo::class);
  }

}